### PR TITLE
Remove leading dollar signs when copying codeblocks

### PR DESCRIPTION
**Pull request by andermi**
Just a bit of javascript hackery!

Works when "triple-clicking" and also clicking on the copy button for clode blocks.
NOTE: it doesn't limit selection of the dollar signs; it just doesn't copy them

e.g.
selected text: (or contents of code block)
```
$ mkdir -p ~/controller_ws/src
$ cd ~/controller_ws/src
```
pasted text:
```
mkdir -p ~/controller_ws/src
cd ~/controller_ws/src
```

### CODE REVIEW

**Comment by andermi** [comment]
Since most browsers (other than Firefox) don't allow multiple (non-contiguous) selection ranges, this is the best I can do without getting into some serious hacking to rewrite the codeblocks to place the `$` in their own table entry. The problem is that if they select multiple lines with `$` on each line, it will modify the selection to only the first line (and correctly without the dollar sign) but still copy both lines (correctly without dollar sign)

**Comment by andermi** [comment]
So, to the user it looks as if it only copied the first line, but in fact copied both lines... should I change it to actually copy only what is selected even if they initially selected multiple?

**Comment by andermi** [comment]
also, I need someone to test on Safari I suppose...

**Comment by hamilton8415** [comment]
Yeah, probably best to only copy what's highlighted, minus the dollar sign of course...  I can check on Safari on my mac...

**Comment by andermi** [comment]
Don't know if this counts, but I tried it in Safari on my iPhone and it works!

**Comment by hamilton8415** [comment]
Totally counts.

**Review by hamilton8415 — APPROVED** [review]
Thanks for doing this

**Comment by mabelzhang** [comment]
Can merge as is, but there is a weird behavior if I highlight and copy multiple lines, e.g.
https://osrf.github.io/mbari_wec/pr-preview/pr-50/Tutorials/Simulation/SimulatorInteractionPbcmd/#example-usage
```
empy -D 'inc_wave_spectrum_type="None"' -o ~/mbari_wec_ws/install/buoy_description/share/buoy_description/models/mbari_wec/model.sdf ~/mbari_wec_ws/install/buoy_description/share/buoy_description/models/mbari_wec/model.sdf.em

ros2 launch buoy_gazebo mbari_wec.launch.py regenerate_models:=false
```
The copy button works. But if I highlight both lines and then Ctrl+C, the result is weird - the highlight changes to first line only, and only the first line is copied.

This could be a new issue to be addressed in the future.

**Comment by andermi** [comment]
@mabelzhang See these comments. That behavior is working as intended although not ideal...

https://github.com/osrf/mbari_wec/pull/50#issuecomment-1539278043

https://github.com/osrf/mbari_wec/pull/50#issuecomment-1539280316

https://github.com/osrf/mbari_wec/pull/50#issuecomment-1540194495

The issue is that none of the browsers allow non-contiguous selection regions (i.e. two lines with a dollar sign in the middle).
I can certainly copy and remove the dollar signs programmatically but the selection buffer doesn't reflect what's copied that way...

**Pull request merged**
