### PR TITLE
update tutorials

### PR DESCRIPTION
**Pull request by andermi**
update tutorials for new pack rate service and use non-blocking for python

### CODE REVIEW

**Review by quarkytale — APPROVED** [review]

**Comment by quarkytale** [comment]
Changes look good to me, but the preview gives 404 for CppTemplate.md url seems to be old https://osrf.github.io/mbari_wec/pr-preview/pr-53/Tutorials/ROS2/CPPTemplate.md. Even when I manually updated its still gives 404. Refreshing didn't work. Same with CppOpenLoopControl.md and ClosedLoopControl.md.

**Comment by andermi** [comment]
> preview gives 404

Can you try again? It shows up fine for me:
https://osrf.github.io/mbari_wec/pr-preview/pr-53/Tutorials/ROS2/CppTemplate/

**Comment by andermi** [comment]
all the links work for me as well

**Comment by quarkytale** [comment]
Nope, tried it on another system too, the tutorial directs to CPPTemplate.md which gives the error and even if I manually change it to CppTemplate same error, something like this, enlarged content and 404 in the end:
buoy404_2
buoy404

**Comment by quarkytale** [comment]
Oh so when I try to go from the dropdown menu and click on `Controller GitHub Template (C++)` it creates a url with `CPPTemplat.md `but instead it should be `CppTemplate/`

**Comment by quarkytale** [comment]
I know what's wrong, you need to update mkdocs.yml as well to generate the correct navigation and links. Sorry I missed it in the review, all changes in tutorials.md should reflect in mkdocs.yml. I can make the quick change if you want.

**Comment by andermi** [comment]
I also just fixed a reference to ignition gazebo and other broken links

**Pull request merged**
